---
- name: Installation of nginx
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: true

  - name: Update the UFW firewall
    shell:
      cmd: ufw allow 'Nginx Full'

  - name: Test and Restart Nginx
    shell: 
      cmd: nginx -t && systemctl restart nginx
