# Build Stage
FROM node:23-alpine AS build

WORKDIR /vue/app

# Copy the package.json files
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

RUN npm run build


# Production Stage
FROM nginx:stable-alpine

# Copy build application to the Nginx container
COPY --from=build /vue/app/dist /usr/share/nginx/html

# Copy the nginx config file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]