#!/usr/bin/env bash
# Include the 301 redirection to our nginx server block

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx Full'

echo "Working on the 301 (The third time). This is the home page" | sudo tee /var/www/html/index.html

# Add the 301 script on the server
replacement="rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/ permanent;\n"

sudo sed -i "s/rewrite ^\/redirect_me https:\/\/github.com\/Mokowz permanent;/$replacement/" /etc/nginx/sites-enabled/default

# Add a custom 404 error page
echo "Eii this is not the right page my guy" | sudo tee /var/www/html/404.html

string_to_replace="rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/ permanent;"
string_replacement="rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/ permanent;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n"

sudo sed -i "s/$string_to_replace/$string_replacement/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo systemctl restart nginx
